### ISSUE TITLE
UnicodeDecodeError when loading README.rst

### ISSUE THREAD

**Issue by kgriffs** [wanadev/pyguetzli#4]
Hi there, I'm getting the following error when trying to install under Python 3 (PyPy3) in Linux:
```
Collecting pyguetzli (from rhith)
  Downloading pyguetzli-1.0.6.tar.gz (106kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qo_bojj7/pyguetzli/setup.py", line 58, in <module>
        long_description = open("README.rst", "r").read()
      File "/opt/pypy3/lib-python/3/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 682: ordinal not in range(128)
```

**Comment by flozz** [comment]
Thank you,

 the fix was released in pyguetzli v1.0.7
